language: python
sudo: required

cache:
- pip

python:
  - 3.6
  - 3.7
  - 3.8

before_install:
  - sudo apt-get install python3-snappy libsnappy-dev

install:
  - pip install -r dev_requirements.txt

script:
  - make test
  - make dist

notifications:
  email:
    on_success: never
    on_failure: never

deploy:
  provider: pypi
  user: wesyoung
  password:
    secure: Mqeuee+rEakkPjPwf2qpapdy9PFDSddQiUFg0lrQu8yVsZrbKto3PLZrGjt40ZbUrtf9Y1ZppZkfZMktNfhUoIi8WaKh/q/fwh2yl2piveuzCQ04NFYFDJGDs/Q+3De3Es4lDcPOkTcRokI+2Okq0pfes+4uIYUqfRw5D5+NZWY059gTABRwJzlKHayg1VplfopSinF2J9tUzN+Laf2E9pMnQyCXwEcf9bwaUFyaSjHC1drwsSHZc/i0felYyD6ppMBAURz1YbfW0Tw9kK5Zod4FJMjXiq/PQJGZPh87MHGwWr4B+H43kYnqlK3B9JqeaRtT4pDRNNUoAgbVmNqklku6AFwUEKLl8XbPjSxJnvPWMW3xE5TCjHLbpySj4yro+TrqXRIm9Ttuva8yOcx+nW4hkkn/8Jv+EWBCy4dw8EQ3DifsfAKrmDNKLef3f9LprVUbQDc1n6mCiQ13qJ549iSCbRTMvO9eUYqY8C4fScY8AZ7mJc8Ep3eUVUg6FsahxiiFLooiAokOTfZYopFBycSsB8OSi05fZdz8zmDJm9FQ3eIXRE4xj827NuWLXWOfXkQyp+quYhij70RG/6ax7OkrpKa24ePBRCV/Weh3PXqtB3HkDX5tjUDs3pvWSTIeSp4k8aod90/QSVPLO7dXXYo+iRe9Lyqn/OZKZ6TkrbI=
  on:
    branch: master
    tags: true
    condition: $TRAVIS_PYTHON_VERSION = "3.7"
