language: python
sudo: required
cache:
- pip
python:
- 3.6
- 3.7
- 3.8
before_install:
- sudo apt-get install libsnappy-dev
install:
- pip install -r dev_requirements.txt
- python setup.py develop
script:
- make test
- make dist
notifications:
  email:
    on_success: never
    on_failure: never
deploy:
  provider: pypi
  user: __token__
  on:
    branch: master
    tags: true
    condition: $TRAVIS_PYTHON_VERSION = "3.7"
  password:
    secure: ttmsXCnfWmYWjYS4ERqsODvvvldBhCI/qkn6iGjaOsOXA/bswucJ9XA3qwkJbefsgkk2I7lm/8bSF8f/8lcY43qGddlLBXQRhmNUEyQyt5bNbvT92TYSrlLERGTAYG9HGizoXuo7+6EVszHApm6mtQxMOKOLQtqbUhqBUxXAAEEjKI5uBq+BZnV636e1vefdsZh9xk5kFNNHM1tboEYYMknMjsTdvrQU6VjIf2icrN0xi8O2bzfEtysU8h1IYsnOUC/eP6YGe9Uvq3FIR7T5aHDAgED50xGAPGf1YZzdhYrffhVAq+exwF4a+qjBCrUYF1ZUAjaURUPtWqmfqzdJTBYd/zaWFD/+7YjiXAaRNDLqI/OygK2C/C9jeWup9WYMdk8PqY5q1oCMBBMqwaDARfD8Db4dXrrrqjd8aoInnslWlLhY9Wj/Hi5GVV0w20/x4PExr5LVH2Esh3i5ZdufB+bgiUeqpvbYBFXpHkpXL3hZKuDrNXffn0PzdNA4qGjeJpEC4hkkmHtabqshy9CHxeF10WCZ5P9T3Vuhn/G74JdwDr2e+/dTrD6xQbZBXB7/x7hfCJGzK1Qme0GlsC4wTnZIR3UCENwiuZTanIS9R5Z/uXM2V3gjbig4irNfEAW+UKIZyimDy7x7zn+/mR+dlpmfGpqFNk07kxqFvKZ5qhY=
